# Check your 'JVM property' if Mojibake still occurs: -Dfile.encoding=<charset>
# https://docs.oracle.com/javase/8/docs/api/java/nio/charset/Charset.html
file-encoding: UTF-8

# Shall we install the game sample?
install-sample: false

# Naming convention of world directories.
world-name: Game

# Specification for every games.
# The root folder is equivalent to: plugins/CraftGames/
# https://en.wikipedia.org/wiki/Path_(computing)#Representations_of_paths_by_operating_system_and_shell
games:
  example: # Title of sample game. Turn on 'install-sample' above to test it!
    layout: Sample/example/layout.yml # Path to layout.yml