# Check your 'JVM property' if Mojibake still occurs: -Dfile.encoding=<charset>
# https://docs.oracle.com/javase/8/docs/api/java/nio/charset/Charset.html
file-encoding: UTF-8


# Shall we install the game sample?
install-sample: false


# Invincible duration (in ticks) applied to a respawning player.
spawn-invincible: 60


# Script Settings
script:

  # Available engines: Groovy, JSR223
  engine: Groovy

  # Toggle verbose output to log file (for debugging purpose)
  debug: false


# The prefix of generated world's directory name.
world-label: game


# Performance Optimization
optimization:

  # Limit the number of mobs alive per each game.
  mob-capacity: 100

  # Limits the number of blocks in one schematic to be processed.
  schematic-throttle: 10000

  # Set how many particles are generated per 1 block while displaying area.
  particle-resolution: 2

  # Set maximum distance for particles to be visible.
  particle-render-distance: 30

  # Set maximum attempt to calculate safe area to spawn a mob/player
  safezone-calculation:
    mob-throttle: 3
    player-throttle: 10


# Default fallback location when leaving game.
#exit-fallback:
#  world: world
#  x: 0.0
#  y: 70.0
#  z: 0.0
#  yaw: 0.0
#  pitch: 0.0


# Game Registration
# Note: The root folder is equivalent to: plugins/CraftGames/
# https://en.wikipedia.org/wiki/Path_(computing)#Representations_of_paths_by_operating_system_and_shell
games:
  example: # Title of sample game. Turn on 'install-sample' above to test it!
    layout: Sample/example/layout.yml # Path to layout.yml
