# Game Registration
# Note: The root folder is equivalent to: plugins/CraftGames/
# https://en.wikipedia.org/wiki/Path_(computing)#Representations_of_paths_by_operating_system_and_shell
games:
  example: # Title of sample game. Turn on 'install-sample' above to test it!
    layout: Sample/example/layout.yml # Path to layout.yml


# The prefix of generated world's directory name.
world-label: game


# Check your 'JVM property' if Mojibake still occurs: -Dfile.encoding=<charset>
# https://docs.oracle.com/javase/8/docs/api/java/nio/charset/Charset.html
file-encoding: UTF-8


# Shall we install the game sample?
install-sample: false


# Invincible duration (in ticks) applied to a respawning player.
spawn-invincible: 60


# Game-Exit Policy
exit-policy:

  # Should player return to the location where he issued /join command?
  record-join-location: true

  # Exit location to use if it isn't be resolved for any reason.
  fallback:
    world: world
    x: 0.0
    y: 0.0
    z: 0.0
    yaw: 0.0
    pitch: 0.0


# Script Control
script:

  # Available engines: Groovy, JSR223
  engine: Groovy

  # Toggle verbose output to log file (for debugging purpose)
  debug: false


# Performance Optimization
optimization:

  # Limit the number of mobs alive per each game. (Script can override this value)
  mob-capacity: 200

  # Limit the number of blocks that can be processed per each schematic.
  schematic-throttle: 10000

  # Set how many particles are generated per block to display area capture.
  particle-resolution: 2

  # Set visibility of artificial particles.
  particle-render-distance: 30

  # Set maximum attempt to calculate safe area before spawning a mob/player
  safezone-calculation:
    mob-throttle: 3
    player-throttle: 10