name: CraftGames
main: com.github.lazoyoung.craftgames.Main
api-version: '1.15'
version: $version
commands:
  game:
    description: Manage games.
    usage: Type /game to see command list.
  coord:
    description: Manage coordinate tags.
    usage: Type /ct to see command list.
    aliases: [ ctag, coordtag ]