name: CraftGames
main: com.github.lazoyoung.craftgames.Main
author: LazoYoung
api-version: '1.15'
version: $version
softdepend: [ WorldEdit, MythicMobs, Vault, LootTableFix ]
commands:
  join:
    description: Join a game.
    usage: /join [game]
    aliases: [ play ]
  leave:
    description: Leave a game.
    usage: /leave
    aliases: [ quit ]
  kit:
    description: Select a kit.
    usage: /kit [name]
  game:
    description: Manage games.
    usage: Type /game to see command list.
  ctag:
    description: Manage coordinate tags.
    usage: Type /ctag to see command list.
    aliases: [ coord, coordtag ]
  mapvote:
    description: Vote for a map inside a game.
    usage: Type /vote to open menu.
    aliases: [ vote ]